x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '4.4.0'
  publishedVersionMetadata:
    releaseNote: >-
      vCluster Platform v4.4.0
  # The images property will be filled in during part 2
  images:
    '':  # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
  clusterPermissions:
    - rules:
        - apiGroups: ["apiregistration.k8s.io"]
          resources: ["apiservices"]
          # Least-privilege: scope to the exact APIService name if possible
          #resourceNames: ["v1.management.loft.sh"]   # <- narrow if you can
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - rules:
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources: ["clusterrolebindings"]
          verbs: ["get","list","watch","create","update","patch"]
  deployerServiceAccount:
    description: >
      Service account for deployer
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ["rbac.authorization.k8s.io", "clusterroles.rbac.authorization.k8s.io"]
        resources: ["*"]
        verbs: ["*"]
      - apiGroups: ["apiregistration.k8s.io", "apiservices.apiregistration.k8s.io"]
        resources: ["*"]
        verbs: ["*"]
      - apiGroups: ["admissionregistration.k8s.io", "mutatingwebhookconfigurations.admissionregistration.k8s.io"]
        resources: ["*"]
        verbs: ["*"]

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
- name
- namespace
